name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: buluma/issue-action@0.1.0
        with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["bug", "error"], "labels": ["BUG"], "assignees": ["buluma"]}, {"keywords": ["help", "guidance"], "labels": ["help-wanted"], "assignees": ["buluma"]}, {"keywords": ["feature", "request"], "labels": ["enhancement"], "assignees": ["buluma"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
